todo/urls.py
from django.urls import path
from .import views

app_name = 'todo'
urlpatterns = [
    path('', views.home, name='home'),
    path('todo/', views.todo, name='todo'),
    path('delete_todo/<int:todo_id>/', views.delete_todo, name='delete_todo'),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    added_date = models.DateTimeField()
    text = models.CharField(max_length=200)

    def __str__(self):
        return '{}'.format(self.text)

todo/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Todo
from django.http import HttpResponseRedirect

# Create your views here.
def home(request):
    todo_items = Todo.objects.all().order_by("-added_date")
    return render(request, 'todo/index.html', {
        "todo_items": todo_items
    })

def todo(request):
    current_date = timezone.now()
    content = request.POST.get('content', False)
    Todo.objects.create(added_date=current_date, text=content)
    Todo.objects.all().count()
    return HttpResponseRedirect("/")

def delete_todo(request, todo_id):
    Todo.objects.get(id=todo_id).delete()
    return HttpResponseRedirect("/")

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <!-- Navbar content -->
        <a class="navbar-brand" href="/">To Do App</a>
    </nav>

    <div class="container">
        {% block content %}
    
        {% endblock content %}
    </div>
    
</body>

templates/todo/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-4">
        <div class="col">
            <h2>Add Item</h2>
            <form action="{% url 'todo:todo' %}" method="post"  class="form-inline">
                {% csrf_token %}
                <input type="text" name="content" class="form-control mb-2" placeholder="type here...">
                <button type="submit" class="btn btn-primary mb-2">Submit</button>
            </form>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <ul class="list-group">
                {% for todo_item in todo_items %}
                    <li class="list-group-item">{{ todo_item.text }}
                        <div class="float-right">
                            <form action="{% url 'todo:delete_todo' todo_item.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </div>
                    </li>    
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock content %}